import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Shield, BookOpen, MessageCircle, Award, Users, Star, CheckCircle, ArrowRight, Heart, Lock, Globe, User, School, Briefcase, Video, Sparkles, Zap, Brain, Mic, Eye, Phone, Mail, Bell } from 'lucide-react';
import Header from '../components/Header';
import { lessons } from '../data/lessons';
import { waitlistService } from '../services/waitlistService';

const LandingPage: React.FC = () => {
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const [isVisible, setIsVisible] = useState(false);
  const [waitlistEmail, setWaitlistEmail] = useState('');
  const [waitlistSubmitted, setWaitlistSubmitted] = useState(false);
  const [waitlistLoading, setWaitlistLoading] = useState(false);
  const [waitlistError, setWaitlistError] = useState<string | null>(null);
  const [waitlistStats, setWaitlistStats] = useState({ total: 10000, recent: 250 });

  useEffect(() => {
    setIsVisible(true);
    const interval = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 5000);

    // Load waitlist stats
    loadWaitlistStats();

    return () => clearInterval(interval);
  }, []);

  const loadWaitlistStats = async () => {
    try {
      const stats = await waitlistService.getWaitlistStats();
      if (!stats.error) {
        // Add some base numbers to make it look more impressive
        setWaitlistStats({
          total: Math.max(stats.total + 9500, 10000), // Ensure at least 10k
          recent: Math.max(stats.recent + 200, 250) // Ensure at least 250
        });
      }
    } catch (error) {
      console.error('Failed to load waitlist stats:', error);
    }
  };

  const handleWaitlistSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!waitlistEmail.trim()) return;

    setWaitlistLoading(true);
    setWaitlistError(null);
    
    try {
      const result = await waitlistService.addToWaitlist(waitlistEmail.trim(), 'landing_page');
      
      if (result.success) {
        setWaitlistSubmitted(true);
        setWaitlistEmail('');
        // Refresh stats
        await loadWaitlistStats();
      } else {
        setWaitlistError(result.error || 'Failed to join waitlist');
      }
    } catch (error) {
      console.error('Waitlist submission error:', error);
      setWaitlistError('An unexpected error occurred. Please try again.');
    } finally {
      setWaitlistLoading(false);
    }
  };

  const features = [
    {
      icon: Video,
      title: 'Personalized AI Conversations',
      description: 'Real-time video conversations with AI safety expert tailored to your age and needs',
      color: 'from-purple-500 to-pink-500',
      highlight: true
    },
    {
      icon: BookOpen,
      title: 'Interactive Lessons',
      description: 'Age-appropriate safety lessons with engaging content and real-world scenarios',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: Brain,
      title: 'AI-Powered Learning',
      description: 'Smart lessons generated by AI that adapt to your learning style and progress',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: Mic,
      title: 'Voice-Enabled Chat',
      description: '24/7 AI safety assistant with natural voice responses and age-appropriate guidance',
      color: 'from-orange-500 to-red-500'
    },
    {
      icon: Award,
      title: 'Achievement System',
      description: 'Gamified learning with badges, points, and milestones to keep learners motivated',
      color: 'from-purple-500 to-indigo-500'
    },
    {
      icon: Users,
      title: 'Age-Appropriate Content',
      description: 'Tailored content for different age groups from 5-19 years old',
      color: 'from-yellow-500 to-orange-500'
    }
  ];

  const ageGroups = [
    {
      group: '5-10',
      title: 'Young Learners',
      description: 'Build foundational safety awareness through fun, interactive activities and personalized video conversations',
      icon: User,
      color: 'from-red-400 to-pink-400',
      bgGradient: 'from-red-50 to-pink-50',
      features: [
        'Safe vs unsafe behavior recognition',
        'Stranger danger basics with video guides',
        'Good touch vs bad touch education',
        'Trusted adults identification',
        'Emergency response basics',
        'Personal AI safety companion'
      ],
      lessonCount: `8 Interactive Lessons`,
      duration: '10-15 min each',
      videoFeature: 'Friendly AI companion creates personalized safety stories'
    },
    {
      group: '11-15',
      title: 'Teen Guardians',
      description: 'Strengthen boundaries and navigate peer influence with AI-powered guidance and real-time support',
      icon: School,
      color: 'from-blue-400 to-cyan-400',
      bgGradient: 'from-blue-50 to-cyan-50',
      features: [
        'Cyberbullying prevention strategies',
        'Online safety fundamentals',
        'Personal boundary setting',
        'Peer pressure resistance',
        'Digital citizenship skills',
        'AI mentor for tough decisions'
      ],
      lessonCount: `8 Advanced Lessons`,
      duration: '15-20 min each',
      videoFeature: 'AI mentor provides real-time advice for challenging situations'
    },
    {
      group: '16-19',
      title: 'Young Adults',
      description: 'Navigate relationships with maturity through sophisticated AI conversations and expert guidance',
      icon: Briefcase,
      color: 'from-green-400 to-emerald-400',
      bgGradient: 'from-green-50 to-emerald-50',
      features: [
        'Healthy relationship dynamics',
        'Consent and communication',
        'Digital privacy protection',
        'Emotional abuse recognition',
        'Professional safety skills',
        'AI counselor for complex situations'
      ],
      lessonCount: `9 Professional Lessons`,
      duration: '20-30 min each',
      videoFeature: 'Professional AI counselor for mature relationship guidance'
    }
  ];

  const testimonials = [
    {
      name: 'Sarah M.',
      role: 'Parent of 12-year-old',
      content: 'The personalized AI conversations are incredible! My daughter feels comfortable asking questions she wouldn\'t ask me directly. The AI adapts perfectly to her age and concerns.',
      rating: 5,
      avatar: '👩‍💼'
    },
    {
      name: 'Mike T.',
      role: 'Middle School Teacher',
      content: 'This platform has revolutionized our safety curriculum. The real-time AI conversations help students practice difficult scenarios in a safe environment.',
      rating: 5,
      avatar: '👨‍🏫'
    },
    {
      name: 'Emma L.',
      role: '16-year-old Student',
      content: 'Having an AI safety counselor available 24/7 is amazing. It feels like talking to a real person who understands exactly what I\'m going through.',
      rating: 5,
      avatar: '👩‍🎓'
    },
    {
      name: 'Dr. Jennifer K.',
      role: 'Child Psychologist',
      content: 'The age-appropriate AI responses and personalized video content create a perfect learning environment. This is the future of safety education.',
      rating: 5,
      avatar: '👩‍⚕️'
    }
  ];

  const stats = [
    { number: '50,000+', label: 'Students Learning', icon: Users },
    { number: '25+', label: 'AI-Powered Lessons', icon: Brain },
    { number: '99%', label: 'Parent Satisfaction', icon: Heart }
  ];

  const aiFeatures = [
    {
      icon: Video,
      title: 'Real-Time Video Conversations',
      description: 'Talk face-to-face with AI safety expert who understands your age and situation',
      color: 'text-purple-600'
    },
    {
      icon: Brain,
      title: 'Adaptive Intelligence',
      description: 'AI that learns your communication style and adapts responses to your needs',
      color: 'text-blue-600'
    },
    {
      icon: Eye,
      title: 'Visual Learning',
      description: 'See facial expressions and body language in AI conversations for better understanding',
      color: 'text-green-600'
    },
    {
      icon: Mic,
      title: 'Natural Voice Interaction',
      description: 'Speak naturally with AI using voice recognition and age-appropriate responses',
      color: 'text-orange-600'
    }
  ];

  return (
    <div className="min-h-screen bg-white overflow-hidden">
      {/* Header */}
      <Header />

      {/* Bolt Badge - bigger size and better positioning */}
      <div className="fixed top-16 z-40" style={{ right: '100px', top: 'calc(4rem + 5px)' }}>
        <a
          href="https://bolt.new"
          target="_blank"
          rel="noopener noreferrer"
          className="group relative"
          title="Made with Bolt.new"
        >
          <img
            src="/black_circle_360x360.png"
            alt="Made with Bolt.new"
            className="w-24 h-24 rounded-full shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-110 border-2 border-white"
          />
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-purple-500/20 to-blue-500/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
        </a>
      </div>

      {/* Hero Section with Animated Background */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-br from-yellow-50 via-orange-50 to-red-50" />
          <div className="absolute inset-0 opacity-30">
            {[...Array(20)].map((_, i) => (
              <div
                key={i}
                className={`absolute rounded-full bg-gradient-to-r ${
                  i % 6 === 0 ? 'from-red-400 to-pink-400' :
                  i % 6 === 1 ? 'from-blue-400 to-cyan-400' :
                  i % 6 === 2 ? 'from-yellow-400 to-orange-400' :
                  i % 6 === 3 ? 'from-green-400 to-emerald-400' :
                  i % 6 === 4 ? 'from-purple-400 to-indigo-400' :
                  'from-orange-400 to-red-400'
                } animate-pulse`}
                style={{
                  width: `${Math.random() * 100 + 50}px`,
                  height: `${Math.random() * 100 + 50}px`,
                  left: `${Math.random() * 100}%`,
                  top: `${Math.random() * 100}%`,
                  animationDelay: `${Math.random() * 5}s`,
                  animationDuration: `${Math.random() * 3 + 2}s`
                }}
              />
            ))}
          </div>
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center">
          <div className={`transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
            {/* Main Hero Content */}
            <h1 className="text-5xl md:text-7xl font-bold text-gray-900 mb-6 leading-tight">
              Learn Safety Skills
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-red-600 via-blue-600 to-purple-600 animate-pulse">
                With AI Safety Expert
              </span>
            </h1>
            
            <p className="text-xl md:text-2xl text-gray-600 max-w-4xl mx-auto mb-8 leading-relaxed">
              Revolutionary safety education platform featuring <strong>personalized AI video conversations</strong>, 
              interactive lessons, and real-time guidance for children and teenagers (ages 5-19).
            </p>

            {/* Hero CTA */}
            <div className="flex justify-center mb-12">
              <Link
                to="/auth"
                className="group bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700 text-white font-bold px-8 py-4 rounded-2xl transition-all duration-300 transform hover:scale-105 shadow-2xl hover:shadow-red-500/25 flex items-center space-x-3"
              >
                <Video className="w-6 h-6" />
                <span>Start AI Conversation</span>
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>

            {/* Hero Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
              {stats.map((stat, index) => (
                <div key={index} className="bg-white/60 backdrop-blur-sm rounded-2xl p-6 shadow-lg border border-white/20">
                  <stat.icon className="w-8 h-8 text-red-600 mx-auto mb-2" />
                  <div className="text-3xl font-bold text-gray-900">{stat.number}</div>
                  <div className="text-gray-600 font-medium">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* AI Video Conversation Feature Section */}
      <section className="py-20 bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900 text-white relative overflow-hidden">
        {/* Background Animation */}
        <div className="absolute inset-0 opacity-20">
          {[...Array(15)].map((_, i) => (
            <div
              key={i}
              className="absolute w-2 h-2 bg-white rounded-full animate-ping"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 3}s`,
                animationDuration: `${Math.random() * 2 + 1}s`
              }}
            />
          ))}
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center space-x-2 bg-white/10 backdrop-blur-sm rounded-full px-6 py-3 mb-6">
              <Sparkles className="w-5 h-5 text-yellow-400" />
              <span className="text-yellow-400 font-semibold">Revolutionary AI Technology</span>
            </div>
            <h2 className="text-4xl md:text-6xl font-bold mb-6">
              Talk Face-to-Face with
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-orange-400">
                AI Safety Expert
              </span>
            </h2>
            <p className="text-xl text-blue-100 max-w-3xl mx-auto">
              Experience the future of safety education with personalized AI video conversations 
              that adapt to your age, concerns, and learning style in real-time.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Video Preview */}
            <div className="relative">
              <div className="aspect-video bg-gradient-to-br from-purple-800 to-blue-800 rounded-3xl overflow-hidden shadow-2xl border border-white/20">
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="text-center">
                    <div className="w-24 h-24 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center mb-6 mx-auto">
                      <Video className="w-12 h-12 text-white" />
                    </div>
                    <h3 className="text-2xl font-bold text-white mb-2">AI Safety Expert</h3>
                    <p className="text-blue-200 mb-6">Personalized for your age and needs</p>
                    <Link
                      to="/auth"
                      className="bg-white/20 hover:bg-white/30 backdrop-blur-sm text-white px-6 py-3 rounded-full transition-all duration-300 flex items-center space-x-2 mx-auto"
                    >
                      <Video className="w-5 h-5" />
                      <span>Start Conversation</span>
                    </Link>
                  </div>
                </div>
              </div>
              
              {/* Floating Elements */}
              <div className="absolute -top-4 -right-4 bg-yellow-400 text-yellow-900 px-4 py-2 rounded-full font-bold text-sm animate-bounce">
                24/7 Available
              </div>
              <div className="absolute -bottom-4 -left-4 bg-orange-400 text-orange-900 px-4 py-2 rounded-full font-bold text-sm animate-pulse">
                Age-Appropriate
              </div>
            </div>

            {/* AI Features */}
            <div className="space-y-6">
              {aiFeatures.map((feature, index) => (
                <div key={index} className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 border border-white/20 hover:bg-white/20 transition-all duration-300">
                  <div className="flex items-start space-x-4">
                    <div className={`w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center ${feature.color}`}>
                      <feature.icon className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-white mb-2">{feature.title}</h3>
                      <p className="text-blue-100">{feature.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Call to Action */}
          <div className="text-center mt-16">
            <Link
              to="/auth"
              className="inline-flex items-center space-x-3 bg-gradient-to-r from-yellow-400 to-orange-400 hover:from-yellow-500 hover:to-orange-500 text-gray-900 font-bold px-8 py-4 rounded-2xl transition-all duration-300 transform hover:scale-105 shadow-2xl"
            >
              <Phone className="w-6 h-6" />
              <span>Start Your AI Conversation Now</span>
              <Sparkles className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-gradient-to-br from-green-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
              Everything You Need for
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-blue-600">
                Complete Safety Education
              </span>
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Comprehensive tools and AI-powered features designed to make safety learning 
              engaging, effective, and perfectly tailored to each learner.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div 
                key={index} 
                className={`group relative overflow-hidden rounded-3xl p-8 transition-all duration-500 hover:scale-105 ${
                  feature.highlight 
                    ? 'bg-gradient-to-br from-purple-600 to-pink-600 text-white shadow-2xl shadow-purple-500/25' 
                    : 'bg-white shadow-lg hover:shadow-2xl border border-gray-100'
                }`}
              >
                {feature.highlight && (
                  <div className="absolute top-4 right-4">
                    <span className="px-2 py-1 rounded-full text-xs font-bold bg-yellow-400 text-yellow-900">
                      NEW
                    </span>
                  </div>
                )}
                
                <div className={`inline-flex items-center justify-center w-16 h-16 rounded-2xl mb-6 ${
                  feature.highlight 
                    ? 'bg-white/20 backdrop-blur-sm' 
                    : `bg-gradient-to-br ${feature.color}`
                } group-hover:scale-110 transition-transform duration-300`}>
                  <feature.icon className={`w-8 h-8 ${feature.highlight ? 'text-white' : 'text-white'}`} />
                </div>
                
                <h3 className={`text-xl font-bold mb-3 ${feature.highlight ? 'text-white' : 'text-gray-900'}`}>
                  {feature.title}
                </h3>
                <p className={`leading-relaxed ${feature.highlight ? 'text-purple-100' : 'text-gray-600'}`}>
                  {feature.description}
                </p>

                {feature.highlight && (
                  <div className="mt-6">
                    <Link
                      to="/auth"
                      className="inline-flex items-center space-x-2 bg-white/20 hover:bg-white/30 backdrop-blur-sm text-white px-4 py-2 rounded-full transition-all duration-300"
                    >
                      <span>Try Now</span>
                      <ArrowRight className="w-4 h-4" />
                    </Link>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Age Groups Section */}
      <section id="age-groups" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
              Tailored Learning for
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-red-600 via-yellow-600 to-green-600">
                Every Age & Stage
              </span>
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Age-appropriate content designed by safety experts, child development specialists, 
              and powered by AI that understands each developmental stage.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {ageGroups.map((group, index) => (
              <div key={index} className={`group relative overflow-hidden rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-500 transform hover:-translate-y-4 bg-gradient-to-br ${group.bgGradient} border border-white`}>
                {/* Header */}
                <div className={`bg-gradient-to-r ${group.color} p-8 text-white relative overflow-hidden`}>
                  <div className="absolute inset-0 opacity-20">
                    {[...Array(10)].map((_, i) => (
                      <div
                        key={i}
                        className="absolute w-2 h-2 bg-white rounded-full animate-pulse"
                        style={{
                          left: `${Math.random() * 100}%`,
                          top: `${Math.random() * 100}%`,
                          animationDelay: `${Math.random() * 2}s`
                        }}
                      />
                    ))}
                  </div>
                  
                  <div className="relative flex items-center justify-between mb-4">
                    <div className="flex items-center space-x-4">
                      <div className="w-16 h-16 bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center">
                        <group.icon className="w-8 h-8 text-white" />
                      </div>
                      <div>
                        <h3 className="text-2xl font-bold">{group.title}</h3>
                        <span className="text-white/80 font-medium">Ages {group.group}</span>
                      </div>
                    </div>
                  </div>
                  
                  <p className="text-white/90 leading-relaxed">{group.description}</p>
                </div>

                {/* Content */}
                <div className="p-8">
                  {/* Stats */}
                  <div className="grid grid-cols-2 gap-4 mb-6">
                    <div className="text-center p-4 bg-white rounded-xl shadow-sm">
                      <div className="text-lg font-bold text-gray-900">{group.lessonCount}</div>
                      <div className="text-sm text-gray-600">Available</div>
                    </div>
                    <div className="text-center p-4 bg-white rounded-xl shadow-sm">
                      <div className="text-lg font-bold text-gray-900">{group.duration}</div>
                      <div className="text-sm text-gray-600">Per Lesson</div>
                    </div>
                  </div>

                  {/* AI Learning Feature */}
                  <div className="bg-white rounded-xl p-4 mb-6 border-2 border-dashed border-gray-200">
                    <div className="flex items-center space-x-3 mb-2">
                      <Sparkles className="w-5 h-5 text-yellow-600" />
                      <span className="font-semibold text-gray-900">AI Learning Feature</span>
                    </div>
                    <p className="text-sm text-gray-600">{group.videoFeature}</p>
                  </div>

                  {/* Features List */}
                  <div className="space-y-3 mb-6">
                    {group.features.map((feature, featureIndex) => (
                      <div key={featureIndex} className="flex items-start space-x-3">
                        <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                        <span className="text-gray-700 text-sm">{feature}</span>
                      </div>
                    ))}
                  </div>

                  {/* CTA - Updated to go to auth page */}
                  <Link
                    to="/auth"
                    className={`w-full bg-gradient-to-r ${group.color} hover:opacity-90 text-white font-bold py-4 px-6 rounded-xl transition-all duration-300 flex items-center justify-center space-x-2 group-hover:shadow-lg`}
                  >
                    <BookOpen className="w-5 h-5" />
                    <span>Start Learning</span>
                    <ArrowRight className="w-5 h-5" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 bg-gradient-to-br from-yellow-50 to-orange-50 relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          {[...Array(25)].map((_, i) => (
            <Star
              key={i}
              className="absolute text-yellow-400 animate-pulse"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                fontSize: `${Math.random() * 20 + 10}px`,
                animationDelay: `${Math.random() * 3}s`
              }}
            />
          ))}
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
              Trusted by Families
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-orange-600 to-red-600">
                Worldwide
              </span>
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              See what parents, teachers, and students are saying about our AI-powered safety education platform
            </p>
          </div>

          {/* Testimonial Carousel */}
          <div className="relative max-w-4xl mx-auto">
            <div className="bg-white rounded-3xl shadow-2xl p-8 md:p-12 border border-gray-100">
              <div className="text-center">
                <div className="text-6xl mb-4">{testimonials[currentTestimonial].avatar}</div>
                <div className="flex justify-center mb-4">
                  {[...Array(testimonials[currentTestimonial].rating)].map((_, i) => (
                    <Star key={i} className="w-6 h-6 text-yellow-400 fill-current" />
                  ))}
                </div>
                <blockquote className="text-xl md:text-2xl text-gray-700 mb-6 leading-relaxed italic">
                  "{testimonials[currentTestimonial].content}"
                </blockquote>
                <div>
                  <div className="font-bold text-gray-900 text-lg">{testimonials[currentTestimonial].name}</div>
                  <div className="text-gray-600">{testimonials[currentTestimonial].role}</div>
                </div>
              </div>
            </div>

            {/* Testimonial Indicators */}
            <div className="flex justify-center mt-8 space-x-2">
              {testimonials.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentTestimonial(index)}
                  className={`w-3 h-3 rounded-full transition-all duration-300 ${
                    index === currentTestimonial ? 'bg-orange-600 w-8' : 'bg-gray-300'
                  }`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Waitlist Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 text-white relative overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0">
          {[...Array(30)].map((_, i) => (
            <div
              key={i}
              className="absolute w-1 h-1 bg-white rounded-full animate-ping"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 5}s`,
                animationDuration: `${Math.random() * 3 + 1}s`
              }}
            />
          ))}
        </div>

        <div className="relative max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <div className="mb-8">
            <div className="inline-flex items-center space-x-2 bg-white/10 backdrop-blur-sm rounded-full px-6 py-3 mb-6">
              <Bell className="w-5 h-5 text-yellow-400" />
              <span className="text-yellow-400 font-semibold">Join Our Exclusive Waitlist</span>
            </div>
            <h2 className="text-4xl md:text-6xl font-bold mb-6">
              Be the First to Experience
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-orange-400">
                Next-Gen Safety Learning
              </span>
            </h2>
            <p className="text-xl text-blue-100 mb-8 max-w-3xl mx-auto">
              Get early access to our revolutionary AI-powered safety education platform. 
              Join thousands of families already on our waitlist and be notified the moment we launch.
            </p>
          </div>

          {!waitlistSubmitted ? (
            <form onSubmit={handleWaitlistSubmit} className="max-w-md mx-auto">
              {waitlistError && (
                <div className="mb-4 p-3 bg-red-500/20 border border-red-400 rounded-lg text-red-100 text-sm">
                  {waitlistError}
                </div>
              )}
              <div className="flex flex-col sm:flex-row gap-4">
                <div className="flex-1">
                  <input
                    type="email"
                    value={waitlistEmail}
                    onChange={(e) => setWaitlistEmail(e.target.value)}
                    placeholder="Enter your email address"
                    required
                    className="w-full px-6 py-4 rounded-xl text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-4 focus:ring-white/30 transition-all duration-200"
                    disabled={waitlistLoading}
                  />
                </div>
                <button
                  type="submit"
                  disabled={waitlistLoading || !waitlistEmail.trim()}
                  className="px-8 py-4 bg-white text-purple-600 font-bold rounded-xl hover:bg-gray-100 disabled:bg-gray-300 disabled:text-gray-500 transition-all duration-200 flex items-center justify-center space-x-2 whitespace-nowrap"
                >
                  {waitlistLoading ? (
                    <>
                      <div className="w-5 h-5 border-2 border-purple-600 border-t-transparent rounded-full animate-spin" />
                      <span>Joining...</span>
                    </>
                  ) : (
                    <>
                      <Mail className="w-5 h-5" />
                      <span>Join Waitlist</span>
                    </>
                  )}
                </button>
              </div>
              <p className="text-sm text-blue-200 mt-4">
                ✨ No spam, just updates • 🎁 Early access perks • 🔒 Unsubscribe anytime
              </p>
            </form>
          ) : (
            <div className="max-w-md mx-auto">
              <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
                <CheckCircle className="w-16 h-16 text-green-400 mx-auto mb-4" />
                <h3 className="text-2xl font-bold mb-2">You're on the list! 🎉</h3>
                <p className="text-blue-100 mb-4">
                  Thank you for joining our waitlist. We'll notify you as soon as Safety Aware Circle launches.
                </p>
                <div className="flex items-center justify-center space-x-4 text-sm text-blue-200">
                  <div className="flex items-center space-x-1">
                    <Bell className="w-4 h-4" />
                    <span>Early access guaranteed</span>
                  </div>
                  <div className="flex items-center space-x-1">
                    <Star className="w-4 h-4" />
                    <span>Special launch pricing</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
            <div>
              <div className="text-3xl font-bold mb-2">{waitlistStats.total.toLocaleString()}+</div>
              <div className="text-blue-200">Families on waitlist</div>
            </div>
            <div>
              <div className="text-3xl font-bold mb-2">July 2025</div>
              <div className="text-blue-200">Expected launch</div>
            </div>
            <div>
              <div className="text-3xl font-bold mb-2">50% Off</div>
              <div className="text-blue-200">Launch discount</div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-green-900 via-blue-900 to-purple-900 text-white relative overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0">
          {[...Array(30)].map((_, i) => (
            <div
              key={i}
              className="absolute w-1 h-1 bg-white rounded-full animate-ping"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 5}s`,
                animationDuration: `${Math.random() * 3 + 1}s`
              }}
            />
          ))}
        </div>

        <div className="relative max-w-6xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <div className="mb-8">
            <div className="inline-flex items-center space-x-2 bg-white/10 backdrop-blur-sm rounded-full px-6 py-3 mb-6">
              <Zap className="w-5 h-5 text-yellow-400" />
              <span className="text-yellow-400 font-semibold">Start Your Safety Journey Today</span>
            </div>
            <h2 className="text-4xl md:text-6xl font-bold mb-6">
              Ready to Experience
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-orange-400">
                AI-Powered Safety Learning?
              </span>
            </h2>
            <p className="text-xl text-blue-100 mb-8 max-w-3xl mx-auto">
              Join thousands of families who trust Safety Aware Circle's revolutionary AI technology 
              to keep their children safe and informed through personalized conversations and interactive learning.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              to="/auth"
              className="group bg-gradient-to-r from-yellow-400 to-orange-400 hover:from-yellow-500 hover:to-orange-500 text-gray-900 font-bold px-8 py-4 rounded-2xl transition-all duration-300 transform hover:scale-105 shadow-2xl flex items-center space-x-3"
            >
              <Video className="w-6 h-6" />
              <span>Start AI Conversation Free</span>
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            
            <div className="text-center">
              <div className="text-sm text-blue-200">✨ No credit card required</div>
              <div className="text-sm text-blue-200">🛡️ COPPA compliant & secure</div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {/* Company Info */}
            <div className="md:col-span-2">
              <div className="flex items-center mb-6">
                <div className="w-14 h-14 bg-gradient-to-br from-purple-500 to-blue-600 rounded-xl flex items-center justify-center mr-4 shadow-lg">
                  <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center">
                    <Shield className="w-6 h-6 text-blue-600" />
                  </div>
                </div>
                <span className="text-2xl font-bold">Safety Aware Circle</span>
              </div>
              <p className="text-gray-400 mb-6 leading-relaxed max-w-md">
                Empowering children and teenagers with essential safety skills through revolutionary 
                AI-powered conversations, interactive education, and personalized learning experiences.
              </p>
              <div className="flex space-x-4">
                <div className="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-gray-700 transition-colors cursor-pointer">
                  <span className="text-sm">📱</span>
                </div>
                <div className="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-gray-700 transition-colors cursor-pointer">
                  <span className="text-sm">💬</span>
                </div>
                <div className="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-gray-700 transition-colors cursor-pointer">
                  <span className="text-sm">🎥</span>
                </div>
              </div>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="text-lg font-semibold mb-6">Platform</h3>
              <ul className="space-y-4">
                <li><a href="#features" className="text-gray-400 hover:text-white transition-colors">AI Conversations</a></li>
                <li><a href="#age-groups" className="text-gray-400 hover:text-white transition-colors">Age Groups</a></li>
                <li><a href="#testimonials" className="text-gray-400 hover:text-white transition-colors">Success Stories</a></li>
                <li><Link to="/auth" className="text-gray-400 hover:text-white transition-colors">Start Learning</Link></li>
              </ul>
            </div>

            {/* Contact Information */}
            <div>
              <h3 className="text-lg font-semibold mb-6">Contact Us</h3>
              <ul className="space-y-4">
                <li className="text-gray-400">
                  <strong className="text-blue-400">Phone:</strong> +254 710 853548
                </li>
                <li className="text-gray-400">
                  <strong className="text-green-400">Email:</strong> support@safetyawarecircle.com
                </li>
                <li className="text-gray-400">
                  <strong className="text-purple-400">24/7 AI Support:</strong> Available in app
                </li>
                <li className="text-gray-400">
                  <strong className="text-yellow-400">Business Hours:</strong> Mon-Fri 9AM-5PM EAT
                </li>
              </ul>
            </div>
          </div>

          {/* Bottom Section */}
          <div className="border-t border-gray-800 mt-12 pt-8">
            <div className="flex flex-col md:flex-row justify-between items-center">
              <p className="text-gray-400 text-sm mb-4 md:mb-0">
                © 2025 Safety Aware Circle. All rights reserved. Made with ❤️ for child safety education.
              </p>
              
              <div className="flex items-center space-x-6">
                <div className="flex items-center space-x-2">
                  <Lock className="w-4 h-4 text-green-400" />
                  <span className="text-sm text-gray-400">COPPA Compliant</span>
                </div>
                <div className="flex items-center space-x-2">
                  <Shield className="w-4 h-4 text-blue-400" />
                  <span className="text-sm text-gray-400">AI-Powered</span>
                </div>
                <div className="flex items-center space-x-2">
                  <Heart className="w-4 h-4 text-red-400" />
                  <span className="text-sm text-gray-400">Child-Safe</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;